const ROLES = {
  SUPERADMIN: 'SUPERADMIN',
  ADMIN:      'ADMIN',
  SUPERVISOR: 'SUPERVISOR',
  INGENIERO:  'INGENIERO',
  CONSULTA:   'CONSULTA',
};

const TIPOS_MOVIMIENTO = {
  ENTRADA:    'ENTRADA',
  SALIDA:     'SALIDA',
  TRASLADO:   'TRASLADO',
  AJUSTE:     'AJUSTE',
  PRESTAMO:   'PRESTAMO',
  DEVOLUCION: 'DEVOLUCION',
};

const ESTADOS_TICKET = { ABIERTO: 'ABIERTO', EN_PROCESO: 'EN_PROCESO', CERRADO: 'CERRADO' };
const PRIORIDADES    = { BAJA: 'BAJA', MEDIA: 'MEDIA', ALTA: 'ALTA', CRITICA: 'CRITICA' };
const TIPOS_ALERTA   = { STOCK_CRITICO: 'STOCK_CRITICO', STOCK_MINIMO: 'STOCK_MINIMO', SIN_STOCK: 'SIN_STOCK' };

module.exports = { ROLES, TIPOS_MOVIMIENTO, ESTADOS_TICKET, PRIORIDADES, TIPOS_ALERTA };
